import startCrollSuave from "./scroll-suave.js";
import startScrollSections from "./scroll-sections.js";
import startTabsImgEtexto from "./imgs-textos.js";
import startFaqPerguntas from "./faq-perguntas.js";
import startTemaEscuro from "./tema-escuro.js";
import startModal from ".//modal.js";
import startToolTip from "./tooltip.js";
import startDropdownMenu from "./dropdownmenu.js";
import startMenuMobile from "./menuMobile.js";
import startAnimaisNumeros from "./animaisNumeros.js";
import startFuncionamento from "./funcionamento.js";
import startBitCoin from "./bitcoin.js";

startCrollSuave();
startScrollSections();
startTabsImgEtexto();
startFaqPerguntas();
startTemaEscuro();
startModal();
startToolTip();
startDropdownMenu();
startMenuMobile();
startAnimaisNumeros();
startFuncionamento();
startBitCoin();
